# Generated by Django 4.2.7 on 2023-11-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reja',
            old_name='detail',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='reja',
            old_name='task',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reja',
            old_name='holat',
            new_name='status',
        ),
    ]
