# Generated by Django 4.2.7 on 2023-11-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_reja_egasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reja',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
