# Generated by Django 4.2.7 on 2023-11-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_alter_reja_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reja',
            name='slug',
            field=models.SlugField(default=2, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
