# Generated by Django 4.2.7 on 2023-11-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_reja_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reja',
            name='slug',
        ),
        migrations.AlterField(
            model_name='reja',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
